// PocketBase migration: create "employees" (flattened) and "verifications" (with verify_by)
migrate(
  (db) => {
    const dao = new Dao(db)

    // employees (flattened fields)
    const employees = new Collection({
      id: 'employees000000',
      name: 'employees',
      type: 'base',
      system: false,
      schema: [
        {
          system: false,
          id: 'fld_ippsid001',
          name: 'ippsId',
          type: 'text',
          required: true,
          unique: true,
          options: { min: null, max: null, pattern: '' },
        },

        {
          system: false,
          id: 'fld_fname001',
          name: 'firstName',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_lname001',
          name: 'lastName',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_dob00001',
          name: 'dateOfBirth',
          type: 'date',
          required: false,
          unique: false,
          options: {},
        },
        {
          system: false,
          id: 'fld_gender01',
          name: 'gender',
          type: 'select',
          required: false,
          unique: false,
          options: { maxSelect: 1, values: ['Male', 'Female', 'Other'] },
        },
        {
          system: false,
          id: 'fld_mstatus1',
          name: 'maritalStatus',
          type: 'select',
          required: false,
          unique: false,
          options: {
            maxSelect: 1,
            values: ['Single', 'Married', 'Divorced', 'Widowed'],
          },
        },
        {
          system: false,
          id: 'fld_nat00001',
          name: 'nationality',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_state001',
          name: 'stateOfOrigin',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_lga00001',
          name: 'lga',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_phone01',
          name: 'phoneNumber',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_email01',
          name: 'email',
          type: 'email',
          required: false,
          unique: false,
          options: {},
        },
        {
          system: false,
          id: 'fld_addr001',
          name: 'residentialAddress',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_nok0001',
          name: 'nextOfKin',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_nokrel1',
          name: 'nextOfKinRelationship',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_profpic',
          name: 'profilePic',
          type: 'file',
          required: false,
          unique: false,
          options: {
            maxSelect: 1,
            maxSize: 5242880,
            mimeTypes: ['image/*'],
            thumbs: [],
          },
        },

        {
          system: false,
          id: 'fld_dofa001',
          name: 'dateOfFirstAppointment',
          type: 'date',
          required: false,
          unique: false,
          options: {},
        },
        {
          system: false,
          id: 'fld_capp001',
          name: 'currentAppointment',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_desig01',
          name: 'designation',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_glevel1',
          name: 'gradeLevel',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_grade01',
          name: 'grade',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_mda0001',
          name: 'mda',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_cdre001',
          name: 'cdre',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_conf001',
          name: 'dateOfConfirmation',
          type: 'date',
          required: false,
          unique: false,
          options: {},
        },
        {
          system: false,
          id: 'fld_retd01',
          name: 'expectedRetirementDate',
          type: 'date',
          required: false,
          unique: false,
          options: {},
        },
        {
          system: false,
          id: 'fld_prom001',
          name: 'dateOfLastPromotion',
          type: 'date',
          required: false,
          unique: false,
          options: {},
        },

        {
          system: false,
          id: 'fld_hqual01',
          name: 'highestQualification',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_inst001',
          name: 'institutionAttended',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_ygrad01',
          name: 'yearOfGraduation',
          type: 'number',
          required: false,
          unique: false,
          options: { min: null, max: null },
        },
        {
          system: false,
          id: 'fld_certs01',
          name: 'professionalCertifications',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_train01',
          name: 'trainingAttended',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },

        {
          system: false,
          id: 'fld_ss00100',
          name: 'salaryStructure',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_basic01',
          name: 'basicSalary',
          type: 'number',
          required: false,
          unique: false,
          options: { min: null, max: null },
        },
        {
          system: false,
          id: 'fld_allow01',
          name: 'allowances',
          type: 'number',
          required: false,
          unique: false,
          options: { min: null, max: null },
        },
        {
          system: false,
          id: 'fld_deduct1',
          name: 'deductions',
          type: 'number',
          required: false,
          unique: false,
          options: { min: null, max: null },
        },
        {
          system: false,
          id: 'fld_netpay1',
          name: 'netPay',
          type: 'number',
          required: false,
          unique: false,
          options: { min: null, max: null },
        },
        {
          system: false,
          id: 'fld_acct01',
          name: 'accountNumber',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_bvn0001',
          name: 'bvn',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_pfa0001',
          name: 'pfaName',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_rsa0001',
          name: 'rsaPin',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_nhis001',
          name: 'nhisNumber',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },

        {
          system: false,
          id: 'fld_pphot01',
          name: 'passportPhotograph',
          type: 'file',
          required: false,
          unique: false,
          options: {
            maxSelect: 1,
            maxSize: 5242880,
            mimeTypes: ['image/*'],
            thumbs: [],
          },
        },
        {
          system: false,
          id: 'fld_fprint1',
          name: 'fingerprints',
          type: 'file',
          required: false,
          unique: false,
          options: {
            maxSelect: 10,
            maxSize: 10485760,
            mimeTypes: ['image/*'],
            thumbs: [],
          },
        },
        {
          system: false,
          id: 'fld_dsign01',
          name: 'digitalSignatures',
          type: 'file',
          required: false,
          unique: false,
          options: {
            maxSelect: 1,
            maxSize: 5242880,
            mimeTypes: ['image/*'],
            thumbs: [],
          },
        },

        {
          system: false,
          id: 'fld_docs001',
          name: 'documents',
          type: 'json',
          required: false,
          unique: false,
          options: {},
        },
        {
          system: false,
          id: 'fld_ndocs01',
          name: 'newDocuments',
          type: 'json',
          required: false,
          unique: false,
          options: {},
        },

        {
          system: false,
          id: 'fld_btype01',
          name: 'bloodType',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_allerg1',
          name: 'allergies',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_emerg01',
          name: 'emergencyContact',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_medhis1',
          name: 'medicalHistory',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },

        {
          system: false,
          id: 'fld_banknm1',
          name: 'bankName',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_branch1',
          name: 'branch',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_ifsc01',
          name: 'ifscCode',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },

        {
          system: false,
          id: 'fld_degree1',
          name: 'degree',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_edins01',
          name: 'educationInstitution',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'fld_yopass1',
          name: 'yearOfPassing',
          type: 'number',
          required: false,
          unique: false,
          options: { min: null, max: null },
        },
        {
          system: false,
          id: 'fld_fgrade1',
          name: 'finalGrade',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
      ],
      indexes: [
        'CREATE UNIQUE INDEX idx_employees_ippsId ON employees (ippsId)',
        'CREATE INDEX idx_employees_bvn ON employees (bvn)',
      ],
      listRule: null,
      viewRule: null,
      createRule: null,
      updateRule: null,
      deleteRule: null,
    })

    dao.saveCollection(employees)

    // verifications
    const verifications = new Collection({
      id: 'verifycoll00000',
      name: 'verifications',
      type: 'base',
      system: false,
      schema: [
        {
          system: false,
          id: 'v_ippsid001',
          name: 'ippsId',
          type: 'text',
          required: true,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'v_empref001',
          name: 'employeeRef',
          type: 'relation',
          required: false,
          unique: false,
          options: {
            collectionId: 'employees000000',
            cascadeDelete: false,
            minSelect: null,
            maxSelect: 1,
            displayFields: [],
          },
        },
        {
          system: false,
          id: 'v_vdata001',
          name: 'verificationData',
          type: 'json',
          required: false,
          unique: false,
          options: {},
        },
        {
          system: false,
          id: 'v_issues001',
          name: 'issues',
          type: 'json',
          required: false,
          unique: false,
          options: {},
        },
        {
          system: false,
          id: 'v_status001',
          name: 'status',
          type: 'select',
          required: true,
          unique: false,
          options: {
            maxSelect: 1,
            values: ['draft', 'submitted', 'approved', 'rejected'],
          },
        },
        {
          system: false,
          id: 'v_subAt001',
          name: 'submittedAt',
          type: 'date',
          required: false,
          unique: false,
          options: {},
        },
        {
          system: false,
          id: 'v_subBy001',
          name: 'submittedBy',
          type: 'text',
          required: false,
          unique: false,
          options: { min: null, max: null, pattern: '' },
        },
        {
          system: false,
          id: 'v_vby000001',
          name: 'verify_by',
          type: 'number',
          required: true,
          unique: false,
          options: { min: null, max: null },
        },
      ],
      indexes: [
        'CREATE INDEX idx_verifications_ippsId ON verifications (ippsId)',
        'CREATE INDEX idx_verifications_verify_by ON verifications (verify_by)',
      ],
      listRule: null,
      viewRule: null,
      createRule: null,
      updateRule: null,
      deleteRule: null,
    })

    dao.saveCollection(verifications)
  },
  (db) => {
    const dao = new Dao(db)
    try {
      const ver = dao.findCollectionByNameOrId('verifycoll00000')
      dao.deleteCollection(ver)
    } catch (e) {}
    try {
      const emp = dao.findCollectionByNameOrId('employees000000')
      dao.deleteCollection(emp)
    } catch (e) {}
  }
)
